kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: acupajoe/nginx-rtmp-streamer
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
